[workspace]
members = [
  "owl",
  "owl-parser",
  "owl-passes",
  "owl-source",
  "owl-value",
  "owl-vm",
]

[profile.release]
# Uncomment when debugging or profiling release build
# debug = true
